name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:      
      matrix:
        builder_type: [local, cloud]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/buildpush
        with:
          builder_type: ${{ matrix.builder_type }}
          platforms: linux/amd64,linux/arm64
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          docker_hub_account: ${{ vars.DOCKER_HUB_ACCOUNT }}
          cloud_builder: ${{ vars.CLOUD_BUILDER }}
